// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duswazdlbdlmfhytivxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1c3dhemRsYmRsbWZoeXRpdnh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMTkzODYsImV4cCI6MjA3MDY5NTM4Nn0.hEjYRTZKzE7RImGpLtaItdai2IOIwqL3CDX7KfZRsEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});